spring:
  application:
    name: security-jwt

  h2:
    console:
      enabled: true

  security:
    config:
      prefix: Bearer
      key: qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890!@#$%^&*()_+qwertyuiopasdfghjklzxcvbnm
      expiration: 3600000

server:
  port: 8081
